# theme: jekyll-theme-minimal
theme: jekyll-theme-cayman
relative_links:
  enabled: true
  collections: true
include:
  # - CONTRIBUTING.md
  - README.md
  # - LICENSE.md
  # - COPYING.md
  # - CODE_OF_CONDUCT.md
  # - CONTRIBUTING.md
  # - ISSUE_TEMPLATE.md
  # - PULL_REQUEST_TEMPLATE.md

logo: /docs/images/backdrops/banner.jpg