# theme: jekyll-theme-minimal
theme: jekyll-theme-cayman
relative_links:
  enabled: true
  collections: true
include:
  # - CONTRIBUTING.md
  - README.md
  # - LICENSE.md
  # - COPYING.md
  # - CODE_OF_CONDUCT.md
  # - CONTRIBUTING.md
  # - ISSUE_TEMPLATE.md
  # - PULL_REQUEST_TEMPLATE.md
sass:
  load_paths:
  - _sass
  - node_modules
# Important for node_modules
exclude: []

logo: /docs/images/backdrops/banner.jpg